services:
  - type: web
    name: codemon
    image:
      url: docker.n8n.io/n8nio/n8n
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: ep-wild-silence-a55hpbl1-pooler.us-east-2.aws.neon.tech
      - key: DB_POSTGRESDB_DATABASE
        value: neondb
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_USER
        value: neondb_owner
      - key: DB_POSTGRESDB_PASSWORD
        value: npg_ElPJAX6hdBK7
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: 'false'
      - key: PORT
        value: 5678
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
